### ISSUE TITLE
Apply Consistent Truepic Styling

### ISSUE THREAD

**Issue by KenCorbettTruepic** [TRUEPIC/remark-automatic-glossary-markup#1]
@jstayton we talked about needing to apply styling consistent with Truepic packages.  Can you give me some direction on how to do that?

**Comment by jstayton** [comment]
Yep, a few things:

- [x] Documentation – both to use the plugin and develop it
- [x] License
- [x] Tests
- [x] ESLint setup for code quality
- [x] Prettier setup for code format
- [x] Release process
- [ ] CircleCI setup to run the tests and linting (quality and format)

You can see (and feel free to steal!) how all that's done in [QueryQL](https://github.com/TRUEPIC/queryql).

Happy to answer any questions!

**Comment by KenCorbettTruepic** [comment]
@jstayton I think I have addressed everything you mentioned except that CircleCI doesn't run.  What do we need to get CircleCI to actually run the build for this package?  I have added the files but it doesn't run.  What more do I need to do?

**Comment by jstayton** [comment]
Looking good!

A few things...

1. The `LICENSE` seems to include the full `README` as well.
2. I don't think you need the `rules` section in `.eslintrc.json`, as that's specific to QueryQL.
3. Prettier has a [pretty good write up](https://prettier.io/docs/en/options.html#print-width) on why `80` is the default `printWidth`. That's what we use in the rest of our JS code, and I think we should continue using it here.
4. For CircleCI, you should just be able to sign up with your GitHub account and have access. Let me know if that doesn't work.
5. It probably makes sense to cut the first release as `1.0.0`? What do you think?
6. You should have an invite to the npm organization.

**Comment by KenCorbettTruepic** [comment]
I have addressed all the issues you raised and have published a 1.0.0 release!  Thanks for all your help with this.
