### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by KenCorbettTruepic** [TRUEPIC/remark-automatic-glossary-markup#2]
I do have tests for this project, but @jstayton can you take a look and make sure they look sufficient to you?

**Comment by jstayton** [comment]
Yep, I think it looks pretty good!

Didn't you say you like colocating the test alongside the source file though? 😎

**Comment by KenCorbettTruepic** [comment]
Good point!!!.... I'll move them to the root.  I had copied an remark plugin starter but I much prefer co-located tests.  I'll get on that.

**Comment by KenCorbettTruepic** [comment]
I think this is addressed now.
