### ISSUE TITLE
Document Release Process

### ISSUE THREAD

**Issue by KenCorbettTruepic** [TRUEPIC/remark-automatic-glossary-markup#3]
It should only take `npm publish` to publish this to NPM but we need to document that in the Readme.  @jstayton is there anything else related to releasing that you would like me to address?

**Comment by jstayton** [comment]
We use a package called [Release It!](https://github.com/release-it/release-it) to automate the release process.

Take a look at the [.release-it.json config file](https://github.com/TRUEPIC/queryql/blob/development/.release-it.json) for QueryQL as a good example. Then an npm [`release` script](https://github.com/TRUEPIC/queryql/blob/development/package.json#L31) runs Release It!.

**Comment by KenCorbettTruepic** [comment]
I just tried it and ReleaseIt worked great!
